# Generated by Django 3.2.8 on 2021-11-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_monthly_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_attendance',
            name='MONTH',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='monthly_attendance',
            name='YEAR',
            field=models.CharField(default='', max_length=25),
        ),
    ]
