# Generated by Django 3.2.8 on 2021-11-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_auto_20211108_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_attendance',
            name='OTHER_DEDUCTION_DESCRIPTION',
            field=models.CharField(max_length=11),
        ),
    ]
