# Generated by Django 3.2.8 on 2021-11-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_alter_monthly_attendance_other_deduction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_attendance',
            name='ABSENT',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthly_attendance',
            name='ADVANCE',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthly_attendance',
            name='BASIC_RATE',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthly_attendance',
            name='DAYS_PRESENT',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthly_attendance',
            name='DIVIDE_BY_DAYS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthly_attendance',
            name='EXTRA_DUTIES',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthly_attendance',
            name='INVENTORY',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthly_attendance',
            name='OTHER_DEDUCTION',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthly_attendance',
            name='OTHER_DEDUCTION_DESCRIPTION',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthly_attendance',
            name='OT_HRS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthly_attendance',
            name='PT',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthly_attendance',
            name='TDS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthly_attendance',
            name='TOTAL_DAYS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthly_attendance',
            name='WEEKLY_OFFS',
            field=models.IntegerField(default=0),
        ),
    ]
