# Generated by Django 3.2.8 on 2022-02-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_auto_20211109_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Table',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ADMIN_NAME', models.CharField(max_length=200)),
                ('ADMIN_ID', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
    ]
