# Generated by Django 3.2.8 on 2022-02-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_auto_20220202_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthly_attendance',
            old_name='ARREARS_WAGES',
            new_name='ABSENT',
        ),
        migrations.RenameField(
            model_name='monthly_attendance',
            old_name='ATTENDANCE_BONUS',
            new_name='ADVANCE',
        ),
        migrations.RenameField(
            model_name='monthly_attendance',
            old_name='ATTENDANCE_INCENTIVE',
            new_name='BASIC_RATE',
        ),
        migrations.RenameField(
            model_name='monthly_attendance',
            old_name='BASIC',
            new_name='DAYS_PRESENT',
        ),
        migrations.RenameField(
            model_name='monthly_attendance',
            old_name='CHILD_EDUCATIONS_ALLOWANCES',
            new_name='DIVIDE_BY_DAYS',
        ),
        migrations.RenameField(
            model_name='monthly_attendance',
            old_name='CONVEYANCE',
            new_name='INVENTORY',
        ),
        migrations.RenameField(
            model_name='monthly_attendance',
            old_name='DEARANCE_ALLOWANCES',
            new_name='OT_HRS',
        ),
        migrations.RenameField(
            model_name='monthly_attendance',
            old_name='FIXED_SALARY',
            new_name='PT',
        ),
        migrations.RenameField(
            model_name='monthly_attendance',
            old_name='HOUSE_RENT_ALLOWANCES',
            new_name='TDS',
        ),
        migrations.RenameField(
            model_name='monthly_attendance',
            old_name='INCENTIVE',
            new_name='TOTAL_DAYS',
        ),
        migrations.RenameField(
            model_name='monthly_attendance',
            old_name='INCOME_TAX',
            new_name='WEEKLY_OFFS',
        ),
        migrations.RemoveField(
            model_name='monthly_attendance',
            name='LABOUR_WELFARE_FUND',
        ),
        migrations.RemoveField(
            model_name='monthly_attendance',
            name='LEAVE_TRAVEL_ALLOWANCES',
        ),
        migrations.RemoveField(
            model_name='monthly_attendance',
            name='LOAN',
        ),
        migrations.RemoveField(
            model_name='monthly_attendance',
            name='MEDICAL_ALLOWANCES',
        ),
        migrations.RemoveField(
            model_name='monthly_attendance',
            name='MONTHLY_BOUNS',
        ),
        migrations.RemoveField(
            model_name='monthly_attendance',
            name='MONTHLY_LEAVE_WAGES',
        ),
        migrations.RemoveField(
            model_name='monthly_attendance',
            name='PROFESSIONAL_TAX',
        ),
        migrations.RemoveField(
            model_name='monthly_attendance',
            name='RELIVER_DUTY_WAGES',
        ),
        migrations.RemoveField(
            model_name='monthly_attendance',
            name='SALARY_ADVANCE',
        ),
        migrations.RemoveField(
            model_name='monthly_attendance',
            name='SHIFT_ALLOWANCES',
        ),
        migrations.RemoveField(
            model_name='monthly_attendance',
            name='SITE_ALLOWANCES',
        ),
        migrations.RemoveField(
            model_name='monthly_attendance',
            name='SPECIAL_ALLOWANCES',
        ),
        migrations.RemoveField(
            model_name='monthly_attendance',
            name='UNIFORM_DEDUCTION',
        ),
        migrations.AddField(
            model_name='monthly_attendance',
            name='OTHER_DEDUCTION_DESCRIPTION',
            field=models.CharField(default='', max_length=100),
        ),
    ]
