# Generated by Django 3.2.8 on 2022-02-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_auto_20220202_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthly_attendance',
            old_name='OVERTIME',
            new_name='OVERTIME_AMOUNT',
        ),
        migrations.RenameField(
            model_name='monthly_attendance',
            old_name='SHIFT_ALLOWANCES',
            new_name='OVERTIME_HRS',
        ),
        migrations.AddField(
            model_name='monthly_attendance',
            name='SHIFT_ALLOWANCES_AMOUNT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthly_attendance',
            name='SHIFT_ALLOWANCES_HRS',
            field=models.IntegerField(default=0),
        ),
    ]
