# Generated by Django 3.2.8 on 2022-02-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0013_auto_20220210_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_details',
            name='ARREARS_WAGES',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='ATTENDANCE_BONUS',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='ATTENDANCE_INCENTIVE',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='BASIC',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='CHILD_EDUCATIONS_ALLOWANCES',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='CONVEYANCE',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='DEARANCE_ALLOWANCES',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='FIXED_SALARY',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='HOUSE_RENT_ALLOWANCES',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='INCENTIVE',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='INCOME_TAX',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='LABOUR_WELFARE_FUND',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='LEAVE_TRAVEL_ALLOWANCES',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='LOAN',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='MEDICAL_ALLOWANCES',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='MONTHLY_BOUNS',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='MONTHLY_LEAVE_WAGES',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='OTHER_ALLOWANCES',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='OTHER_DEDUCTION',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='OVERTIME_AMOUNT',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='PROFESSIONAL_TAX',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='RELIVER_DUTY_WAGES',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='SALARY_ADVANCE',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='SHIFT_ALLOWANCES_AMOUNT',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='SITE_ALLOWANCES',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='SPECIAL_ALLOWANCES',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_details',
            name='UNIFORM_DEDUCTION',
            field=models.CharField(default='', max_length=150),
        ),
    ]
