# Generated by Django 3.2.8 on 2022-02-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0014_auto_20220214_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_Attendance_Table',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMP_CODE', models.CharField(max_length=50)),
                ('DAYS_PRESENT', models.IntegerField(default=0)),
                ('OVERTIME_HRS', models.IntegerField(default=0)),
                ('SHIFT_ALLOWANCES_HRS', models.IntegerField(default=0)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'emp_monthly_attendance_table',
            },
        ),
        migrations.DeleteModel(
            name='monthly_attendance',
        ),
    ]
