# Generated by Django 3.2.8 on 2022-02-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0015_auto_20220214_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_attendance_table',
            name='MONTH',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='monthly_attendance_table',
            name='YEAR',
            field=models.CharField(default='', max_length=25),
        ),
    ]
