# Generated by Django 3.2.8 on 2022-02-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0016_auto_20220214_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_company_details',
            name='DATE_OF_EXIT',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='emp_company_details',
            name='REASON_OF_EXIT',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='emp_personal_details',
            name='MARK_OF_IDENTIFICATION',
            field=models.CharField(default='', max_length=150),
        ),
    ]
