# Generated by Django 3.2.8 on 2022-02-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0018_auto_20220223_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Table',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMP_CODE', models.CharField(max_length=50)),
                ('EMP_NAME', models.CharField(max_length=50)),
                ('LOAN_AMOUNT', models.IntegerField(default=0)),
                ('NO_OF_INSTALLMENT', models.IntegerField(default=0)),
                ('APPLY_DATE', models.CharField(default='', max_length=25)),
                ('CLOSE_DATE', models.CharField(default='', max_length=25)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'emp_loan_table',
            },
        ),
    ]
