# Generated by Django 3.2.8 on 2022-02-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0020_loan_table_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_table',
            name='CLIENT',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='loan_table',
            name='UNIT',
            field=models.CharField(default='', max_length=150),
        ),
    ]
