# Generated by Django 3.2.9 on 2022-04-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0023_remove_salary_details_professional_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_details',
            name='PROFESSIONAL_TAX',
            field=models.CharField(default='', max_length=150),
        ),
    ]
