# Generated by Django 3.2.9 on 2022-04-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0025_remove_salary_details_provident_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_details',
            name='PROVIDENT_FUND',
            field=models.CharField(default='', max_length=150),
        ),
    ]
