# Generated by Django 3.2.9 on 2022-04-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0026_salary_details_provident_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_details',
            name='GROSS_SALARY',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='salary_details',
            name='TOTAL_EARN',
            field=models.CharField(default='', max_length=150),
        ),
    ]
