# Generated by Django 3.2.9 on 2022-04-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0028_remove_salary_details_gross_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_details',
            name='TOTAL_DEDUCATION',
            field=models.CharField(default='', max_length=150),
        ),
    ]
