# Generated by Django 3.2.9 on 2022-05-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0032_remove_monthly_attendance_table_emp_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Customer_Reg',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CLIENT_NAME', models.CharField(max_length=50)),
                ('EMAIL', models.IntegerField(default=0)),
                ('DOB', models.IntegerField(default=0)),
                ('CONTACT_NO', models.IntegerField(default=0)),
                ('WEB', models.CharField(default='', max_length=25)),
                ('GENTER', models.CharField(default='', max_length=25)),
                ('EMERGENCY_CONTACT_NO', models.CharField(default='', max_length=25)),
                ('ADDRESS', models.CharField(default='', max_length=25)),
                ('CLIENT_TYPE', models.CharField(default='', max_length=25)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'customer_reg',
            },
        ),
    ]
