# Generated by Django 3.2.9 on 2022-05-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0034_auto_20220512_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New_Customer_Reg',
        ),
        migrations.AddField(
            model_name='new_emp_reg',
            name='EXPERIANCE',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='new_emp_reg',
            name='PROFESSIONAL_QUALIFICATION',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='new_emp_reg',
            name='ROLE',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='new_emp_reg',
            name='WEB',
            field=models.CharField(default='', max_length=150),
        ),
    ]
