# Generated by Django 3.2.9 on 2022-05-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0036_new_customer_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_emp_reg',
            name='PROFESSIONAL_QUALIFICATION',
        ),
        migrations.RemoveField(
            model_name='new_emp_reg',
            name='ROLE',
        ),
        migrations.RemoveField(
            model_name='new_emp_reg',
            name='WEB',
        ),
    ]
