# Generated by Django 3.2.9 on 2022-05-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0037_auto_20220516_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_details',
            name='DESIGNATION',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='salary_details',
            name='EMP_NAME',
            field=models.CharField(default='', max_length=150),
        ),
    ]
