# Generated by Django 3.2.9 on 2022-05-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0038_auto_20220517_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_details',
            name='UPDATE_DATE',
            field=models.CharField(default='', max_length=150),
        ),
    ]
