# Generated by Django 3.2.9 on 2022-05-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0039_salary_details_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary_details',
            old_name='UPDATE_DATE',
            new_name='SALARY_UPDATE_DATE',
        ),
    ]
