# Generated by Django 3.2.9 on 2022-05-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0040_rename_update_date_salary_details_salary_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_details',
            name='DESIGNATION',
        ),
        migrations.RemoveField(
            model_name='salary_details',
            name='EMP_NAME',
        ),
    ]
