# Generated by Django 3.2.9 on 2022-05-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0042_emp_increment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMP_BONUS_DETAILS',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMP_CODE', models.CharField(default='', max_length=120)),
                ('EMP_NAME', models.CharField(default='', max_length=150)),
                ('DESIGNATION', models.CharField(default='', max_length=150)),
                ('OLD_SALARY', models.CharField(default='', max_length=100)),
                ('INCREMENT_AMOUNT', models.CharField(default='', max_length=100)),
                ('CURRENT_SALARY', models.CharField(default='', max_length=100)),
                ('INCREMENT_PURPOSE', models.CharField(default='', max_length=200)),
                ('INCREMENT_UPDATE_DATE', models.CharField(default='', max_length=100)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'emp_bonus_details',
            },
        ),
        migrations.AddField(
            model_name='salary_details',
            name='EXTRA_BOUNS',
            field=models.CharField(default='', max_length=150),
        ),
    ]
