# Generated by Django 3.2.9 on 2022-05-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0043_auto_20220520_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_bonus_details',
            old_name='CURRENT_SALARY',
            new_name='BONUS_AMOUNT',
        ),
        migrations.RenameField(
            model_name='emp_bonus_details',
            old_name='INCREMENT_PURPOSE',
            new_name='BONUS_DESCRIPTION',
        ),
        migrations.RenameField(
            model_name='emp_bonus_details',
            old_name='INCREMENT_AMOUNT',
            new_name='BONUS_NAME',
        ),
        migrations.RenameField(
            model_name='emp_bonus_details',
            old_name='INCREMENT_UPDATE_DATE',
            new_name='BONUS_UPDATE_DATE',
        ),
        migrations.RemoveField(
            model_name='emp_bonus_details',
            name='OLD_SALARY',
        ),
    ]
