# Generated by Django 3.2.9 on 2022-05-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0044_auto_20220520_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMP_LOAN_DETAILS',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMP_CODE', models.CharField(default='', max_length=120)),
                ('EMP_NAME', models.CharField(default='', max_length=150)),
                ('DESIGNATION', models.CharField(default='', max_length=150)),
                ('LOAN_NAME', models.CharField(default='', max_length=100)),
                ('LOAN_AMOUNT', models.CharField(default='', max_length=100)),
                ('NUMBER_OF_INSTALLMENT', models.CharField(default='', max_length=100)),
                ('AMOUNT_OF_INSTALLMENT', models.CharField(default='', max_length=100)),
                ('REMAINING_OF_INSTALLMENT', models.CharField(default='', max_length=100)),
                ('LOAN_DESCRIPTION', models.CharField(default='', max_length=200)),
                ('LOAN_ADDED_DATE', models.CharField(default='', max_length=100)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'emp_loan_details',
            },
        ),
    ]
