# Generated by Django 3.2.9 on 2022-05-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0045_emp_loan_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMP_ADVANCE_DETAILS',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMP_CODE', models.CharField(default='', max_length=120)),
                ('EMP_NAME', models.CharField(default='', max_length=150)),
                ('DESIGNATION', models.CharField(default='', max_length=150)),
                ('ADVANCE_AMOUNT', models.CharField(default='', max_length=100)),
                ('REMAINING_AMOUNT', models.CharField(default='', max_length=100)),
                ('LAST_ADVANCE_UPDATED', models.CharField(default='', max_length=100)),
                ('ADVANCE_ADDED_DATE', models.CharField(default='', max_length=100)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'emp_advance_details',
            },
        ),
    ]
