# Generated by Django 3.2.9 on 2022-05-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0050_auto_20220525_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_daily_attendance_list',
            name='ATTENDANCE_MONTH',
            field=models.CharField(default='', max_length=100),
        ),
    ]
