# Generated by Django 3.2.9 on 2022-05-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0051_emp_daily_attendance_list_attendance_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMP_EXPENSE_DETAILS',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMP_CODE', models.CharField(default='', max_length=120)),
                ('EMP_NAME', models.CharField(default='', max_length=150)),
                ('DESIGNATION', models.CharField(default='', max_length=150)),
                ('EXPENSE_DATE', models.CharField(default='', max_length=100)),
                ('EXPENSE_AMOUNT', models.CharField(default='', max_length=100)),
                ('EXPENSE_PURPOSE', models.CharField(default='', max_length=100)),
                ('REMARK', models.CharField(default='', max_length=200)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'emp_expense_details',
            },
        ),
    ]
