# Generated by Django 3.2.9 on 2022-06-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0052_emp_expense_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXPENSE_CATEGORY_LIST',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EXP_CODE', models.CharField(default='', max_length=120)),
                ('EXP_PURPOSE', models.CharField(default='', max_length=150)),
                ('CREATED_BY', models.CharField(default='', max_length=150)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'expense_category_list',
            },
        ),
    ]
