# Generated by Django 3.2.9 on 2022-06-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0053_expense_category_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense_category_list',
            name='EXP_CODE',
        ),
    ]
