# Generated by Django 3.2.9 on 2022-06-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0056_leave_application_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_application_list',
            name='REASON',
            field=models.CharField(default='', max_length=350),
        ),
    ]
