# Generated by Django 3.2.9 on 2022-06-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0060_monthly_attendance_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_attendance_details',
            name='MONTH_YEAR',
            field=models.CharField(default='', max_length=150),
        ),
    ]
