# Generated by Django 3.2.9 on 2022-06-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0061_monthly_attendance_details_month_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_daily_attendance_list',
            old_name='LEAVE_CATEGORY',
            new_name='ATTENDANCE_STATUS',
        ),
    ]
