# Generated by Django 3.2.9 on 2022-06-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0063_rename_leave_category_emp_daily_attendance_updated_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_attendance_details',
            name='TOTAL_LEAVE',
            field=models.CharField(default='', max_length=150),
        ),
    ]
