# Generated by Django 3.2.9 on 2022-06-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0064_monthly_attendance_details_total_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMP_CERTIFICATE_DETAILS',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMP_CODE', models.CharField(default='', max_length=120)),
                ('EMP_NAME', models.CharField(default='', max_length=150)),
                ('DESIGNATION', models.CharField(default='', max_length=150)),
                ('CERTIFICATE_TYPE', models.CharField(default='', max_length=100)),
                ('CERTIFICATE_DESCRIPTION', models.CharField(default='', max_length=200)),
                ('ADD_DATE', models.CharField(default='', max_length=100)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'emp_certificate_details',
            },
        ),
    ]
