# Generated by Django 3.2.9 on 2022-06-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0067_remove_leave_category_list_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMP_AWARD_LIST',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMP_CODE', models.CharField(default='', max_length=120)),
                ('EMP_NAME', models.CharField(default='', max_length=150)),
                ('DESIGNATION', models.CharField(default='', max_length=150)),
                ('AWARD_CATEGORY', models.CharField(default='', max_length=100)),
                ('GIFT', models.CharField(default='', max_length=100)),
                ('AWARD_MONTH', models.CharField(default='', max_length=100)),
                ('AWARD_DETAILS', models.CharField(default='', max_length=100)),
                ('AWARD_STATUS', models.CharField(default='', max_length=200)),
                ('AWARD_ADD_DATE', models.CharField(default='', max_length=100)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'emp_award_list',
            },
        ),
    ]
