# Generated by Django 3.2.9 on 2022-06-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0068_emp_award_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_award_list',
            old_name='AWARD_DETAILS',
            new_name='AWARD_DESCRIPTION',
        ),
    ]
