# Generated by Django 3.2.9 on 2022-06-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0069_rename_award_details_emp_award_list_award_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOTICE_BOARD',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TITLE', models.CharField(default='', max_length=120)),
                ('DESCRIPTION', models.CharField(default='', max_length=150)),
                ('CREATED_AT', models.CharField(default='', max_length=150)),
                ('STATUS', models.CharField(default='', max_length=150)),
                ('ADDED_DATE', models.CharField(default='', max_length=150)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'notice_board',
            },
        ),
    ]
