# Generated by Django 3.2.9 on 2022-06-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0071_remove_notice_board_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_board',
            name='DESCRIPTION',
            field=models.CharField(default='', max_length=600),
        ),
    ]
