# Generated by Django 3.2.9 on 2022-06-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0074_alter_manage_folders_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_emp_reg',
            name='AGE',
            field=models.CharField(default='', max_length=12),
        ),
    ]
