# Generated by Django 3.2.9 on 2022-06-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0076_auto_20220628_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_files',
            name='UPLOAD_FILE_URL',
            field=models.CharField(default='', max_length=300),
        ),
    ]
