# Generated by Django 3.2.9 on 2022-06-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0077_manage_files_upload_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_files',
            name='FOLDER_NAME',
            field=models.CharField(default='', max_length=120),
        ),
    ]
