# Generated by Django 3.2.9 on 2022-06-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0078_manage_files_folder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOLIDAYS',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('HOLIDAY_NAME', models.CharField(default='', max_length=120)),
                ('DESCRIPTION', models.CharField(default='', max_length=600)),
                ('HOLIDAY_DATE', models.CharField(default='', max_length=150)),
                ('STATUS', models.CharField(default='', max_length=150)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'holidays',
            },
        ),
    ]
