# Generated by Django 3.2.9 on 2022-07-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0079_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENT_TYPE',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CLIENT_TYPE', models.CharField(default='', max_length=120)),
                ('DESCRIPTION', models.CharField(default='', max_length=600)),
                ('CREATED_AT', models.CharField(default='', max_length=150)),
                ('STATUS', models.CharField(default='', max_length=150)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'client_type',
            },
        ),
    ]
