# Generated by Django 3.2.9 on 2022-07-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0082_designation_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation_list',
            name='DESCRIPTION',
            field=models.CharField(default='', max_length=300),
        ),
    ]
