# Generated by Django 3.2.9 on 2022-07-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0083_designation_list_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PERSONAL_EVENT',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EVENT_NAME', models.CharField(default='', max_length=120)),
                ('START_DATE', models.CharField(default='', max_length=120)),
                ('END_DATE', models.CharField(default='', max_length=120)),
                ('DESCRIPTION', models.CharField(default='', max_length=600)),
                ('CREATED_AT', models.CharField(default='', max_length=150)),
                ('STATUS', models.CharField(default='', max_length=150)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'personal_event',
            },
        ),
    ]
