# Generated by Django 3.2.9 on 2022-07-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0085_attendance_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='WORKING_DAY',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('SUNDAY', models.CharField(default='', max_length=120)),
                ('MONDAY', models.CharField(default='', max_length=120)),
                ('TUESDAY', models.CharField(default='', max_length=120)),
                ('WEDNESDAY', models.CharField(default='', max_length=120)),
                ('THURSDAY', models.CharField(default='', max_length=120)),
                ('FRIDAY', models.CharField(default='', max_length=120)),
                ('SATURDAY', models.CharField(default='', max_length=120)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'working_day',
            },
        ),
    ]
