# Generated by Django 3.2.9 on 2022-07-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0086_working_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodect',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('PRODECT_NAME', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
