# Generated by Django 3.2.9 on 2022-07-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0087_prodect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ITEM_NAME', models.CharField(max_length=200)),
                ('PRODECT_NAME', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
