# Generated by Django 3.2.9 on 2022-07-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0088_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Prodect',
        ),
    ]
