# Generated by Django 3.2.9 on 2022-07-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0089_auto_20220713_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='CITY_LIST',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CITY_NAME', models.CharField(max_length=200)),
                ('STATE_NAME', models.CharField(max_length=200)),
                ('COUNTRY_NAME', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'city_list',
            },
        ),
        migrations.CreateModel(
            name='COUNTRY_LIST',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('COUNTRY_NAME', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'country_list',
            },
        ),
        migrations.CreateModel(
            name='STATE_LIST',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('STATE_NAME', models.CharField(max_length=200)),
                ('COUNTRY_NAME', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'state_list',
            },
        ),
    ]
