# Generated by Django 3.2.9 on 2022-07-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0091_auto_20220718_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state_list',
            name='STATE_ID',
        ),
        migrations.AddField(
            model_name='state_list',
            name='STATE_CODE',
            field=models.CharField(default='', max_length=50),
        ),
    ]
