# Generated by Django 3.2.9 on 2022-07-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0092_auto_20220718_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state_list',
            old_name='STATE_CODE',
            new_name='STATE_ID',
        ),
    ]
