# Generated by Django 3.2.9 on 2022-08-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0095_client_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_details',
            name='CLIENT_ID',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='CLIENT',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='COUNTRY_NAME',
            field=models.CharField(default='', max_length=200),
        ),
    ]
