# Generated by Django 3.2.9 on 2022-08-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0096_auto_20220804_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMP_SALARY_MAINTAINS',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMP_CODE', models.CharField(max_length=50)),
                ('FIXED_SALARY', models.CharField(default='', max_length=150)),
                ('BASIC', models.CharField(default='', max_length=150)),
                ('DEARANCE_ALLOWANCES', models.CharField(default='', max_length=150)),
                ('SPECIAL_ALLOWANCES', models.CharField(default='', max_length=150)),
                ('HOUSE_RENT_ALLOWANCES', models.CharField(default='', max_length=150)),
                ('CONVEYANCE', models.CharField(default='', max_length=150)),
                ('OTHER_ALLOWANCES', models.CharField(default='', max_length=150)),
                ('OVERTIME_AMOUNT', models.CharField(default='', max_length=150)),
                ('SITE_ALLOWANCES', models.CharField(default='', max_length=150)),
                ('SHIFT_ALLOWANCES_AMOUNT', models.CharField(default='', max_length=150)),
                ('INCENTIVE', models.CharField(default='', max_length=150)),
                ('LEAVE_TRAVEL_ALLOWANCES', models.CharField(default='', max_length=150)),
                ('MEDICAL_ALLOWANCES', models.CharField(default='', max_length=150)),
                ('CHILD_EDUCATIONS_ALLOWANCES', models.CharField(default='', max_length=150)),
                ('ATTENDANCE_BONUS', models.CharField(default='', max_length=150)),
                ('ATTENDANCE_INCENTIVE', models.CharField(default='', max_length=150)),
                ('MONTHLY_BOUNS', models.CharField(default='', max_length=150)),
                ('EXTRA_BOUNS', models.CharField(default='', max_length=150)),
                ('MONTHLY_LEAVE_WAGES', models.CharField(default='', max_length=150)),
                ('PF', models.CharField(default='', max_length=150)),
                ('PROFESSIONAL_TAX', models.CharField(default='', max_length=150)),
                ('TOTAL_DEDUCATION', models.CharField(default='', max_length=150)),
                ('TOTAL_EARN', models.CharField(default='', max_length=150)),
                ('NET_PAY', models.CharField(default='', max_length=150)),
                ('ESIC', models.CharField(default='', max_length=150)),
                ('RELIVER_DUTY_WAGES', models.CharField(default='', max_length=150)),
                ('ARREARS_WAGES', models.CharField(default='', max_length=150)),
                ('PROVIDENT_FUND', models.CharField(default='', max_length=150)),
                ('LABOUR_WELFARE_FUND', models.CharField(default='', max_length=150)),
                ('INCOME_TAX', models.CharField(default='', max_length=150)),
                ('LOAN', models.CharField(default='', max_length=150)),
                ('SALARY_ADVANCE', models.CharField(default='', max_length=150)),
                ('OTHER_DEDUCTION', models.CharField(default='', max_length=150)),
                ('UNIFORM_DEDUCTION', models.CharField(default='', max_length=150)),
                ('SALARY_UPDATE_DATE', models.CharField(default='', max_length=150)),
                ('DAYS_PRESENT', models.CharField(default='', max_length=150)),
                ('OVERTIME_HRS', models.CharField(default='', max_length=150)),
                ('SHIFT_ALLOWANCES_HRS', models.CharField(default='', max_length=150)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
            options={
                'db_table': 'emp_salary_maintains',
                'managed': True,
            },
        ),
    ]
