# Generated by Django 3.2.9 on 2022-08-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0098_user_register_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_salary_maintains',
            name='MONTH_SALARY',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='salary_details',
            name='MONTH_SALARY',
            field=models.CharField(default='', max_length=150),
        ),
    ]
