# Generated by Django 3.2.9 on 2022-08-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0099_auto_20220817_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_salary_maintains',
            name='PF',
        ),
        migrations.RemoveField(
            model_name='new_emp',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='salary_details',
            name='PF',
        ),
    ]
