# Generated by Django 3.2.9 on 2022-08-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0100_auto_20220823_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='BANK_LIST',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('BANK_NAME', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'bank_name_list',
            },
        ),
    ]
