# Generated by Django 3.2.9 on 2022-09-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0101_bank_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_details',
            name='ADDRESS',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client_details',
            name='CONTACT_NO',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client_details',
            name='E_MAIL',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client_details',
            name='WEB',
            field=models.CharField(default='', max_length=200),
        ),
    ]
