# Generated by Django 3.2.9 on 2022-09-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0103_emp_company_details_company_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_company_details',
            name='COMPANY_ADDRESS',
        ),
    ]
