# Generated by Django 3.2.8 on 2022-11-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0104_remove_emp_company_details_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_details',
            name='NAMINE_E_NAME',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='salary_details',
            name='NAMINE_E_RELATIONS',
            field=models.CharField(default='', max_length=150),
        ),
    ]
