# Generated by Django 3.2.8 on 2022-11-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0105_auto_20221101_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_salary_maintains',
            name='PENSION_AMOUNT',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='salary_details',
            name='PENSION_AMOUNT',
            field=models.CharField(default='', max_length=150),
        ),
    ]
