from django.conf.urls.static import static
from django.urls import path
from DjangoProject import settings
from hrm import views, sample_view
from hrm import gv_form
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

    # Auhentication Url
    path('login/', views.loginPage, name="login"),
    path('register/', views.registerPage, name="register"),
    path('logout/', views.logoutUser, name="logout"),
    path('upload/', views.upload_file_local, name="upload"),
    # Home Page Url
    path('', views.index, name='index'),
    # Edit Personal Details
    path('Employee_List/', views.employee_list, name='Employee_List'),
    path('New_Employee_Reg/', views.new_employee_register, name='New_Employee_Reg'),
    path('Employees_Management/', views.employees_management, name='Employees_Management'),
    path('Filter_Employees/', views.Filter_Employees, name='Filter_Employees'),
    path('Edit_Employees/', views.edit_employees, name='Edit_Employees'),
    path('Delete_Employees/', views.delete_employees, name='Delete_Employees'),
    path('New_Customer_Reg/', views.new_customer_register, name='New_Customer_Reg'),
    path('Client_Details/', views.client_details, name='Client_Details'),
    path('Edit_Client_Details/', views.edit_client_details, name='Edit_Client_Details'),
    path('Add_City/', views.add_city, name='Add_City'),
    path('Client_List/', views.client_list, name='Client_List'),
    path('Country_List/', views.country_list, name='Country_List'),
    path('Edit_Country_List/', views.edit_country_list, name='Edit_Country_List'),
    path('Attendance_Setting/', views.attendance_setting, name='Attendance_Setting'),
    path('Set_Working_Day/', views.working_day, name='Set_Working_Day'),
    path('Event_List/', views.event_list, name='Event_List'),
    path('Add_Event/', views.add_event, name='Add_Event'),
    path('Edit_Event/', views.edit_event, name='Edit_Event'),
    path('Designation_List/', views.designation_list, name='Designation_List'),
    path('Add_Designation/', views.add_designation, name='Add_Designation'),
    path('Edit_Designation/', views.edit_designation, name='Edit_Designation'),
    path('Award_Category_List/', views.award_category_list, name='Award_Category_List'),
    path('Add_Award_Category/', views.add_award_category, name='Add_Award_Category'),
    path('Edit_Award_Category/', views.edit_award_category, name='Edit_Award_Category'),
    path('Add_Client_Type/', views.add_client_type, name='Add_Client_Type'),
    path('Client_Type_List/', views.client_type_list, name='Client_Type_List'),
    path('Edit_Client_Type/', views.edit_client_type, name='Edit_Client_Type'),
    path('Add_Holidays/', views.add_holidays, name='Add_Holidays'),
    path('Holidays_List/', views.holidays_list, name='Holidays_List'),
    path('Edit_Holiday_Status/', views.edit_holiday_status, name='Edit_Holiday_Status'),
    path('Add_Bank/', views.add_bank, name='Add_Bank'),
    path('File_Management/', views.file_management, name='File_Management'),
    path('Add_File/', views.add_file, name='Add_File'),
    path('Delete_File/', views.delete_file, name='Delete_File'),
    path('Add_Notice/', views.new_notice, name='Add_Notice'),
    path('Download_File', views.download_file, name='Download_File'),
    path('Notice_List/', views.notice_list, name='Notice_List'),
    path('Edit_Notice_Status/', views.edit_notice_status, name='Edit_Notice_Status'),
    path('New_Award/', views.new_award, name='New_Award'),
    path('Award_List/', views.award_list, name='Award_List'),
    path('Edit_Award_List/', views.edit_award, name='Edit_Award_List'),
    path('Employee_Certificate/', views.add_certificate, name='Employee_Certificate'),
    path('Certificate_List/', views.certificate_list, name='Certificate_List'),
    path('Edit_Certificate/', views.edit_certificate, name='Edit_Certificate'),
    path('Add_Leave_Category/', views.new_leave_gategory, name='Add_Leave_Category'),
    path('Leave_Category_List/', views.leave_category_list, name='Leave_Category_List'),
    path('Edit_Leave_Category/', views.edit_leave_category, name='Edit_Leave_Category'),
    path('Leave_Application_List/', views.leave_application_list, name='Leave_Application_List'),
    path('New_Application_List/', views.new_leave_application, name='New_Application_List'),
    path('Edit_Application_List/', views.edit_leave_application, name='Edit_Application_List'),
    path('Attendance_Report/', views.attendance_report, name='Attendance_Report'),
    path('Month_Attendance_Report/', views.month_attendance_report, name='Month_Attendance_Report'),
    path('Filter_Month_Attendance_Report/', views.Filter_month_attendance_report, name='Filter_Month_Attendance_Report'),
    path('Add_Expense_Category/', views.new_excepense_category, name='Add_Expense_Category'),
    path('Expense_Category_List/', views.expense_category_list, name='Expense_Category_List'),
    path('Edit_Expense_Category/', views.edit_expense_category, name='Edit_Expense_Category'),
    path('Add_Expense/', views.new_excepense, name='Add_Expense'),
    path('Expense_List/', views.expense_list, name='Expense_List'),
    path('Edit_Expense/', views.edit_expense, name='Edit_Expense'),
    path('New_Increment/', views.new_increment_list, name='New_Increment'),
    path('Add_Increment/', views.new_increment, name='Add_Increment'),
    path('New_Bonus/', views.new_bonus_list, name='New_Bonus'),
    path('Add_Bonus/', views.new_bonus, name='Add_Bonus'),
    path('Edit_Bonus/', views.edit_bonus, name='Edit_Bonus'),
    path('Manuel_Setting/', views.manuel_setting, name='Manuel_Setting'),
    path('DailY_Attendance_Manegment/', views.daily_attendance_manegement, name='DailY_Attendance_Manegment'),
    path('DailY_Attendance_List/', views.daily_att_list, name='DailY_Attendance_List'),
    path('Edit_Daily_Attendance/', views.daily_att_edit, name='Edit_Daily_Attendance'),
    path('Update_Daily_Attendance/', views.daily_att_update, name='Update_Daily_Attendance'),
    path('Loan_List/', views.loan_list, name='Loan_List'),
    path('Add_Loan/', views.add_loan, name='Add_Loan'),
    path('Edit_Loan/', views.edit_loan, name='Edit_Loan'),
    path('View_Loan/', views.loan_view, name='View_Loan'),
    path('Advance_List/', views.advance_list, name='Advance_List'),
    path('Add_Advance/', views.add_advance, name='Add_Advance'),
    path('Edit_Advance/', views.edit_advance, name='Edit_Advance'),
    path('Salary_Sheet/', views.salary_sheet, name='Salary_Sheet'),
    path('Manage_Customer/', views.manage_customer_register, name='Manage_Customer'),
    path('View_Client/', views.client_view, name='View_Client'),
    path('Employee_Salary_Details/', views.employee_salary_list, name='Employee_Salary_Details'),
    path('Filter_Employee_Salary_Details/', views.fiter_emp_salary_list, name='Filter_Employee_Salary_Details'),
    path('Edit_Customer_Reg/', views.edit_customer, name='Edit_Customer_Reg'),
    path('Employee_Edit/', views.edit_employee_details, name='Employee_Edit'),
    path('Employee_Police_Verification/', views.edit_employee_po_ver_edit, name='Employee_Police_Verification'),
    path('Employee_Address/', views.edit_employee_add_edit, name='Employee_Address'),
    path('Monthly_Attendance/', views.employee_monthly_attendance, name='Monthly_Attendance'),
    path('Monthly_Attendance_Edit/', views.employee_monthly_attendance_edit, name='Monthly_Attendance_Edit'),
    path('Salary_Slip/', views.salary_slip, name='Salary_Slip'),
    path('salary_slip_invoice/', views.salary_slip_invoice, name='salary_slip_invoice'),
    path('Employee_Report/', views.Employee_Report, name='Employee_Report'),
    #path('Admin_Control/', views.Admin_Control, name='Admin_Control'),
    path('Employee_salary_edit/', views.edit_employee_salary_edit, name='Employee_salary_edit'),
    # Country,State,City DropDown Details
    path('add/', views.person_create_view, name='city_add'),
    path('getState/', views.getState, name='getState'),
    path('getState1/', views.getState1, name='getState1'),
    path('getCountry/', views.getCountry, name='getCountry'),
    path('getCity/', views.getCity, name='getCity'),
    path('getBranch/', views.getBranch, name='getBranch'),
    path('getArea/', views.getArea, name='getArea'),
    path('getUnit/', views.getUnit, name='getUnit'),
    path('getUser/', gv_form.getUser, name='getUser'),
    path('Delete_Employees_All/', views.delete_all_employees, name='Delete_Employees_All'),
    path('Delete_Employees_Attendance/', views.delete_all_employees_attendance, name='Delete_Employees_Attendance'),
    path('Insert_Country/', views.Insert_Country, name='Insert_Country'),
    path('Insert_CLIENT/', views.Insert_CLIENT, name='Insert_CLIENT'),
    path('Form_A/', gv_form.form_a, name='Form_A'),
    path('Filter_Form_A/', gv_form.Filter_Form_A, name='Filter_Form_A'),
    path('Form_D/', gv_form.Form_D, name='Form_D'),
    path('Filter_Form_D/', gv_form.Filter_Form_D, name='Filter_Form_D'),
    path('Form_B/', gv_form.Form_B, name='Form_B'),
    path('Filter_Form_B/', gv_form.Filter_Form_B, name='Filter_Form_B'),
    path('Loan_Apply/', gv_form.Loan_Apply, name='Loan_Apply'),
    path('Form_C/', gv_form.Form_C, name='Form_C'),
    path('Form_XXIII/', gv_form.Form_23, name='Form_XXIII'),
    path('Filter_Form_23/', gv_form.Filter_Form_23, name='Filter_Form_23'),
    path('Form_PT/', gv_form.form_pt, name='Form_PT'),
    path('Filter_Form_PF/', gv_form.Filter_Form_PF, name='Filter_Form_PF'),
    path('Form_LWF/', gv_form.form_lwf, name='Form_LWF'),
    path('Filter_Form_LWF/', gv_form.Filter_Form_LWF, name='Filter_Form_LWF'),
    path('Form_PF/', gv_form.form_pf, name='Form_PF'),
    path('Filter_Form_PT/', gv_form.Filter_Form_PT, name='Filter_Form_PT'),
    path('Form_ESI/', gv_form.form_esi, name='Form_ESI'),
    path('Filter_Form_ESI/', gv_form.Filter_Form_ESI, name='Filter_Form_ESI'),
    url(r'^export/csv/$', gv_form.file_load_view, name='export_data'),
    url(r'^export/xls/$', gv_form.export_movies_to_xlsx, name='export_users_xls'),
    path('export/', sample_view.export,name='export'),
    path('export_file', sample_view.simple_upload, name='export_file'),
    path('bulk_emp_attendance', sample_view.monthly_Att_upload, name='bulk_emp_attendance'),
    path('sample_emp_format', sample_view.download_file, name='sample_emp_format'),
    path('sample_emp_att_format', sample_view.download_att_file, name='sample_emp_att_format'),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
handler404 = 'hrm.views.error_404_view'
"""
   path('register/', views.registerPage, name="register"),
   path('login/', views.loginPage, name="login"),
   path('logout/', views.logoutUser, name="logout"),

   # path('',include("django.contrib.auth.urls")),
   path('student_registeration', views.student_registeration,name='student_registeration'),
   path('search_students', views.search_students, name='search_students'),
   path('fees_collection', views.fees_collection, name='fees_collection'),
   path('adminpanel', views.adminpanel, name='adminpanel'),
   path('invoice', views.invoice, name='invoice'),
   path('sendmail', views.send_mail, name='sendmail'),
   path('exportcsv', views.exportcsv, name='exportcsv'),
   path('outstandingfees', views.outstandingfees, name='outstandingfees'),
   path('studentupload', views.simple_upload, name='studentupload'),
   path('export/', views.export),
   url(r'broadcast$', views.broadcast_sms, name="broadcast"),
   url('broadcastmail', views.broadcast_mail, name="broadcastmail"),
   """


